name: Bunker Planner PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ### Terraform Check ###
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Checkout source code"
        run: |
          cd generator/
          yarn install 
          yarn build 
          cd .. 
          zip -r generator.zip generator/build/
          zip -r generator.zip generator/node_modules/
      - uses: actions/upload-artifact@v3
        with:
          name: lambda-requirements
          retention-days: 5
          path: generator.zip
